//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labrador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_List
    {
        public int ID_List { get; set; }
        public int ID_Reader_List { get; set; }
        public int ID_Book_List { get; set; }
        public System.DateTime Date_of_Recieve { get; set; }
        public System.DateTime Date_of_Return { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
