//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labrador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Book_List = new HashSet<Book_List>();
        }
    
        public int ID_Book { get; set; }
        public string Book_Name { get; set; }
        public System.DateTime Release_Date { get; set; }
        public int Price { get; set; }
        public int New_Edition_Flag { get; set; }
        public string Description { get; set; }
        public int ID_Author_Book { get; set; }
        public int Last_Changes_By { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_List> Book_List { get; set; }
    }
}
