//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labrador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader()
        {
            this.Book_List = new HashSet<Book_List>();
        }
    
        public int ID_Reader { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public int Last_Changes_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_List> Book_List { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
